using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ModularMonolith.Users.Domain;
using ModularMonolith.Users.Domain.ValueObjects;
using ModularMonolith.Shared.Domain;

namespace ModularMonolith.Users.Infrastructure.Configurations;

/// <summary>
/// Entity Framework configuration for User entity
/// </summary>
public class UserConfiguration : BaseEntityConfiguration<User>
{
    protected override void ConfigureEntity(EntityTypeBuilder<User> builder)
    {
        builder.ToTable("Users");
        
        // Primary key configuration is handled by base class
        builder.Property(u => u.Id)
            .ValueGeneratedNever(); // UUID v7 generated by BaseEntity using Guid.CreateVersion7()
            
        // Email value object configuration
        builder.Property(u => u.Email)
            .HasConversion(
                email => email.Value,
                value => Email.From(value))
            .HasMaxLength(255)
            .IsRequired();
            
        builder.HasIndex(u => u.Email)
            .IsUnique()
            .HasFilter("\"IsDeleted\" = false"); // PostgreSQL partial index for non-deleted users only
        
        // Password value object configuration
        builder.Property(u => u.Password)
            .HasConversion(
                password => password.Value,
                value => HashedPassword.From(value))
            .HasMaxLength(255)
            .IsRequired();
        
        // UserProfile value object configuration (owned entity)
        builder.OwnsOne(u => u.Profile, profile =>
        {
            profile.Property(p => p.FirstName)
                .HasColumnName("FirstName")
                .HasMaxLength(100)
                .IsRequired();
                
            profile.Property(p => p.LastName)
                .HasColumnName("LastName")
                .HasMaxLength(100)
                .IsRequired();
        });

            
        builder.Property(u => u.LastLoginAt)
            .HasColumnType("timestamptz")
            .IsRequired(false);
        
        // Base entity properties (timestamps and audit fields) are configured by base class
        // Override timestamp configuration to use PostgreSQL timestamptz
        builder.Property(u => u.CreatedAt)
            .HasColumnType("timestamptz");
            
        builder.Property(u => u.UpdatedAt)
            .HasColumnType("timestamptz");
            
        builder.Property(u => u.DeletedAt)
            .HasColumnType("timestamptz");
        
        // Navigation properties temporarily disabled to resolve EF Core mapping issues

    }
}