using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ModularMonolith.Roles.Domain;
using ModularMonolith.Roles.Domain.ValueObjects;
using ModularMonolith.Shared.Domain;

namespace ModularMonolith.Roles.Infrastructure.Configurations;

/// <summary>
/// Entity Framework configuration for Role entity
/// </summary>
public class RoleConfiguration : BaseEntityConfiguration<Role>
{
    protected override void ConfigureEntity(EntityTypeBuilder<Role> builder)
    {
        builder.ToTable("Roles");
        
        // Primary key configuration is handled by base class
        builder.Property(r => r.Id)
            .ValueGeneratedNever(); // UUID v7 generated by BaseEntity using Guid.CreateVersion7()
            
        // RoleName value object configuration
        builder.Property(r => r.Name)
            .HasConversion(
                name => name.Value,
                value => RoleName.From(value))
            .HasMaxLength(100)
            .IsRequired();
            
        builder.HasIndex(r => r.Name)
            .IsUnique()
            .HasDatabaseName("IX_Roles_Name");
        
        // Simple properties
        builder.Property(r => r.Description)
            .HasMaxLength(500)
            .IsRequired();
        
        // Base entity properties (timestamps and audit fields) are configured by base class
        // Override timestamp configuration to use PostgreSQL timestamptz
        builder.Property(r => r.CreatedAt)
            .HasColumnType("timestamptz");
            
        builder.Property(r => r.UpdatedAt)
            .HasColumnType("timestamptz");
            
        builder.Property(r => r.DeletedAt)
            .HasColumnType("timestamptz");
        
        // Navigation properties temporarily disabled to resolve EF Core mapping issues

    }
}